name: Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package(s) are affected?
      multiple: true
      options:
        - '@formkit-gov/core'
        - '@formkit-gov/react'
        - '@formkit-gov/store'
        - '@formkit-gov/wizard'
        - '@formkit-gov/openapi'
        - '@formkit-gov/validators'
        - '@formkit-gov/test-utils'
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: '1.0.0'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Import component '...'
        2. Pass props '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: input
    id: reproduction-link
    attributes:
      label: Reproduction Link
      description: |
        Please provide a link to a CodeSandbox, StackBlitz, or GitHub repo that reproduces the issue.
        This greatly helps us investigate the problem.
      placeholder: 'https://codesandbox.io/...'

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide relevant environment information:
      value: |
        - OS: [e.g., macOS 14.0]
        - Node.js: [e.g., 20.10.0]
        - Browser: [e.g., Chrome 120]
        - React: [e.g., 18.2.0]

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using the latest version of the package
          required: false
