name: Feature Request
description: Suggest a new feature or improvement
title: '[Feature]: '
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package(s) would this feature affect?
      multiple: true
      options:
        - '@formkit-gov/core'
        - '@formkit-gov/react'
        - '@formkit-gov/store'
        - '@formkit-gov/wizard'
        - '@formkit-gov/openapi'
        - '@formkit-gov/validators'
        - '@formkit-gov/test-utils'
        - Documentation
        - New Package
        - Other
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New component
        - New hook
        - New utility
        - API enhancement
        - Performance improvement
        - Developer experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: 'I would like to see...'
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: |
        If applicable, show what the API might look like.
      placeholder: |
        ```tsx
        import { NewFeature } from '@formkit-gov/react';

        <NewFeature prop="value" />
        ```
      render: tsx

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: willingness
    attributes:
      label: Contribution
      description: Are you willing to contribute this feature?
      options:
        - "Yes, I'd like to implement this"
        - 'Yes, with guidance'
        - 'No, but I can help test'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the documentation
          required: true
